language: python
sudo: false
services:
  - docker
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip3 install --upgrade pip
  - pip3 install grpcio
  - make bblfsh/libuast
  - pip3 install . --upgrade
script:
  - python3 setup.py build_ext -i
  - python3 -m unittest discover .
notifications:
  email: false