language: python
sudo: true
dist: xenial
services:
  - docker
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - wget https://github.com/bblfsh/client-python/releases/download/v2.2.1/protobuf-python_3.4.1-1_amd64.deb
  - sudo dpkg -i protobuf-python_3.4.1-1_amd64.deb
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - python3 setup.py --getdeps --log
  - pip3 install . --upgrade
  - if [[ -z "$TRAVIS_TAG" ]]; then exit 0; fi
  - echo "[distutils]" > .pypirc
  - echo "index-servers = " >> .pypirc
  - echo "  pypi" >> .pypirc
  - echo "[pypi]" >> .pypirc
  - echo "username=$PYPI_USER" >> .pypirc
  - echo "password=$PYPI_PASS" >> .pypirc
  - HOME=. python setup.py sdist upload
script:
  - python3 setup.py build_ext -i
  - python3 -m unittest discover .
notifications:
  email: false
