language: python
sudo: true
dist: xenial
env: 
- BBLFSHD_VERSION=v2.9.1 BBLFSH_PYTHON_VERSION=v2.3.0
services:
  - docker
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.6"
  - "3.7"
install:
  - docker run --privileged -d -p 9432:9432 --name bblfshd bblfsh/bblfshd:$BBLFSHD_VERSION
  - docker exec bblfshd bblfshctl driver install bblfsh/python-driver:$BBLFSH_PYTHON_VERSION
  - wget https://github.com/bblfsh/client-python/releases/download/v2.2.1/protobuf-python_3.4.1-1_amd64.deb
  - sudo dpkg -i protobuf-python_3.4.1-1_amd64.deb
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - python3 setup.py --getdeps --log
  - pip3 install . --upgrade
  - cd bblfsh && python3 -m unittest discover
  - if [[ -z "$TRAVIS_TAG" ]]; then exit 0; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '3.6' ]]; then exit 0; fi # disable double uploads to pypi
  - echo "[distutils]" > .pypirc
  - echo "index-servers = " >> .pypirc
  - echo "  pypi" >> .pypirc
  - echo "[pypi]" >> .pypirc
  - echo "username=$PYPI_USER" >> .pypirc
  - echo "password=$PYPI_PASS" >> .pypirc
  - cd ..
  - HOME=. python setup.py sdist upload
script:
  - python3 setup.py build_ext -i
notifications:
  email: false
